import React, { useState } from 'react';
import { Database, Server, Key, Shield, Layers, Code, Copy, Check, Film, HardDrive, Zap } from 'lucide-react';

interface DatabaseArchitectureModalProps {
  isOpen: boolean;
  onClose: () => void;
}

export const DatabaseArchitectureModal: React.FC<DatabaseArchitectureModalProps> = ({
  isOpen,
  onClose
}) => {
  const [activeSchemaTab, setActiveSchemaTab] = useState<'sql' | 'firestore' | 'storage' | 'flow'>('storage');
  const [copied, setCopied] = useState(false);

  if (!isOpen) return null;

  const sqlSchemaCode = `-- ==========================================
-- AURAMAX DATABASE ARCHITECTURE (PostgreSQL / Supabase)
-- ==========================================

-- 1. USERS & PROFILES TABLE
CREATE TABLE public.users (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  username VARCHAR(32) UNIQUE NOT NULL,
  display_name VARCHAR(64) NOT NULL,
  avatar_url TEXT DEFAULT '',
  bio VARCHAR(255) DEFAULT '',
  aura INTEGER NOT NULL DEFAULT 0,
  tier VARCHAR(16) NOT NULL DEFAULT 'npc', -- 'npc', 'rising', 'god', 'cosmic'
  daily_aura_earned INTEGER NOT NULL DEFAULT 0,
  social_aura_earned INTEGER NOT NULL DEFAULT 0,
  discipline_aura_earned INTEGER NOT NULL DEFAULT 0,
  streak INTEGER NOT NULL DEFAULT 0,
  last_active_date DATE DEFAULT CURRENT_DATE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 2. AURA SOCIAL POSTS TABLE (With 8s Video Support & CDN Metadata)
CREATE TABLE public.posts (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  caption TEXT NOT NULL,
  media_url TEXT NOT NULL,                    -- CDN URL from Object Storage (S3 / R2 / Firebase)
  media_type VARCHAR(16) NOT NULL DEFAULT 'image', -- 'image' | 'video'
  video_duration NUMERIC(4,2) DEFAULT NULL,   -- In seconds (max 8.00s)
  thumbnail_url TEXT DEFAULT NULL,            -- Fast preview image generated by worker
  tags TEXT[] DEFAULT '{}',
  aura_gain INTEGER NOT NULL DEFAULT 0,
  plus_votes INTEGER NOT NULL DEFAULT 0,
  minus_votes INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 3. COMMUNITY VOTES TABLE (+ AURA / - AURA)
CREATE TABLE public.votes (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  post_id UUID NOT NULL REFERENCES public.posts(id) ON DELETE CASCADE,
  user_id UUID NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  vote_type VARCHAR(8) NOT NULL CHECK (vote_type IN ('+aura', '-aura')),
  delta INTEGER NOT NULL, -- +100 for '+aura' | -50 for '-aura'
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT unique_user_post_vote UNIQUE(post_id, user_id)
);

-- 4. AURA DISCIPLINA (HABIT TRACKER) TABLE
CREATE TABLE public.habits (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  title VARCHAR(120) NOT NULL,
  category VARCHAR(32) NOT NULL,
  icon VARCHAR(32) DEFAULT 'Zap',
  aura_reward INTEGER NOT NULL DEFAULT 150,
  completed_dates DATE[] DEFAULT '{}',
  streak INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 5. AUDIT & AURA TRANSACTION LOGS
CREATE TABLE public.aura_logs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  amount INTEGER NOT NULL,
  source VARCHAR(32) NOT NULL,
  description TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- REALTIME TRIGGER: Update author's Aura and Tier on vote
CREATE OR REPLACE FUNCTION update_user_aura_on_vote()
RETURNS TRIGGER AS $$
BEGIN
  UPDATE public.users
  SET 
    aura = GREATEST(0, aura + NEW.delta),
    social_aura_earned = GREATEST(0, social_aura_earned + NEW.delta),
    tier = CASE 
      WHEN (aura + NEW.delta) >= 10000 THEN 'cosmic'
      WHEN (aura + NEW.delta) >= 5000 THEN 'god'
      WHEN (aura + NEW.delta) >= 1000 THEN 'rising'
      ELSE 'npc'
    END
  WHERE id = (SELECT user_id FROM public.posts WHERE id = NEW.post_id);
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;`;

  const firestoreSchemaCode = `// ==========================================
// AURAMAX FIRESTORE NO-SQL ARCHITECTURE
// ==========================================

// Collection: /users/{userId}
{
  username: string,         // e.g. "alex_sigma"
  displayName: string,      // e.g. "Alex Rivers"
  avatarUrl: string,        // Storage bucket URL
  bio: string,              // "⚡ Disciplina > Motivação"
  aura: number,             // Total computed Aura score
  tier: "npc" | "rising" | "god" | "cosmic",
  dailyAuraEarned: number,
  socialAuraEarned: number,
  disciplineAuraEarned: number,
  streak: number,
  lastActiveDate: string,
  createdAt: timestamp
}

// Collection: /posts/{postId}
{
  userId: string,           // Author UID
  caption: string,          // Post text
  mediaUrl: string,         // CDN / Storage URL (e.g. https://storage.auramax.app/v/8s_gym.mp4)
  mediaType: "image" | "video",
  videoDuration: 7.8,       // Strict max: 8.0 seconds
  tags: string[],           // ["#GymSigma", "#AuraGain"]
  auraGain: number,         // Net points earned (+1850)
  plusVotes: number,        // Count of +Aura votes
  minusVotes: number,       // Count of -Aura votes
  createdAt: timestamp
}

// Collection: /posts/{postId}/votes/{userId}
{
  userId: string,
  voteType: "+aura" | "-aura",
  delta: number,            // +100 or -50
  timestamp: timestamp
}

// Collection: /habits/{habitId}
{
  userId: string,
  title: string,            // "Treino de Força no Ginásio"
  category: "fitness" | "mind" | "routine" | "diet" | "productivity",
  auraReward: number,       // +200 Aura
  completedDates: string[], // ["2026-08-23", "2026-08-22"]
  streak: number
}`;

  const storagePipelineCode = `// ==========================================
// FLUXO DE UPLOAD & ARMAZENAMENTO (8s VÍDEO & FOTOS)
// ==========================================

1. CLIENTE (Browser / Mobile):
   - Valida duração do vídeo localmente (<video>.duration <= 8.0s).
   - Rejeita vídeos > 8s antes de gastar dados móveis ou banda.
   - Solicita ao servidor uma URL assinada (Pre-signed Upload URL).

2. OBJECT STORAGE (Firebase Cloud Storage / Cloudflare R2 / AWS S3):
   - O arquivo binário (MP4/WebM/JPG) é enviado DIRETO para o Bucket S3/R2.
   - O Storage distribui o ficheiro através de uma CDN global com cache em borda.
   - Retorna a URL pública: "https://cdn.auramax.app/media/posts/user_99_clip.mp4"

3. BASE DE DADOS (PostgreSQL / Firestore):
   - Apenas grava os METADADOS em texto leve (~500 bytes por linha):
     {
       "id": "post_789",
       "user_id": "usr_alex",
       "media_url": "https://cdn.auramax.app/media/posts/user_99_clip.mp4",
       "media_type": "video",
       "video_duration": 7.8,
       "plus_votes": 0,
       "minus_votes": 0
     }

4. PORQUE A BASE DE DADOS AGUENTA COM FOLGA?
   - A base de dados NUNCA armazena arquivos pesados em si.
   - 1 Milhão de posts em metadados pesam apenas ~500 Megabytes!
   - 8 segundos de vídeo pesam apenas 2MB ~ 4MB (ao contrário de vídeos de 1 minuto que pesam 60MB+).
   - Resultado: 0 lag, carregamento em 50ms e custo de infraestrutura quase nulo.`;

  const handleCopy = () => {
    let textToCopy = sqlSchemaCode;
    if (activeSchemaTab === 'firestore') textToCopy = firestoreSchemaCode;
    if (activeSchemaTab === 'storage') textToCopy = storagePipelineCode;

    navigator.clipboard?.writeText?.(textToCopy);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/85 backdrop-blur-md animate-in fade-in duration-200">
      <div className="w-full max-w-2xl bg-neutral-900 border border-white/10 rounded-3xl p-6 shadow-2xl space-y-4 max-h-[90vh] overflow-y-auto">
        {/* Header */}
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-2.5">
            <div className="p-2 rounded-xl bg-amber-400/10 text-amber-400 border border-amber-400/20">
              <Database className="w-5 h-5" />
            </div>
            <div>
              <h3 className="text-lg font-black italic tracking-tight uppercase text-white">
                Arquitetura de Dados & Vídeo (AuraMax)
              </h3>
              <p className="text-xs text-neutral-400">
                Especificação técnica: Object Storage, Vídeos 8s, PostgreSQL e Firestore
              </p>
            </div>
          </div>
          <button
            onClick={onClose}
            className="text-neutral-500 hover:text-neutral-300 p-2 text-base font-bold"
          >
            ✕
          </button>
        </div>

        {/* Navigation Tabs */}
        <div className="grid grid-cols-2 sm:grid-cols-4 gap-1 bg-neutral-950 p-1 rounded-2xl border border-white/10 text-xs font-mono font-bold">
          <button
            onClick={() => setActiveSchemaTab('storage')}
            className={`py-1.5 px-2 rounded-xl transition-all flex items-center justify-center gap-1.5 ${
              activeSchemaTab === 'storage'
                ? 'bg-amber-400 text-black shadow-md'
                : 'text-neutral-400 hover:text-white'
            }`}
          >
            <HardDrive className="w-3.5 h-3.5" />
            Vídeos 8s & Storage
          </button>
          <button
            onClick={() => setActiveSchemaTab('sql')}
            className={`py-1.5 px-2 rounded-xl transition-all flex items-center justify-center gap-1.5 ${
              activeSchemaTab === 'sql'
                ? 'bg-amber-400 text-black shadow-md'
                : 'text-neutral-400 hover:text-white'
            }`}
          >
            <Server className="w-3.5 h-3.5" />
            PostgreSQL DDL
          </button>
          <button
            onClick={() => setActiveSchemaTab('firestore')}
            className={`py-1.5 px-2 rounded-xl transition-all flex items-center justify-center gap-1.5 ${
              activeSchemaTab === 'firestore'
                ? 'bg-amber-400 text-black shadow-md'
                : 'text-neutral-400 hover:text-white'
            }`}
          >
            <Layers className="w-3.5 h-3.5" />
            Firestore NoSQL
          </button>
          <button
            onClick={() => setActiveSchemaTab('flow')}
            className={`py-1.5 px-2 rounded-xl transition-all flex items-center justify-center gap-1.5 ${
              activeSchemaTab === 'flow'
                ? 'bg-amber-400 text-black shadow-md'
                : 'text-neutral-400 hover:text-white'
            }`}
          >
            <Shield className="w-3.5 h-3.5" />
            Regras do Glow
          </button>
        </div>

        {/* Tab Content */}
        {activeSchemaTab === 'storage' ? (
          <div className="space-y-3 bg-neutral-950 p-4 rounded-2xl border border-white/10 text-xs text-neutral-300 leading-relaxed">
            <div className="space-y-1.5">
              <h4 className="font-bold text-amber-400 font-mono text-sm flex items-center gap-1.5">
                <Film className="w-4 h-4 text-amber-400" />
                Como as Fotos e Vídeos de 8s ficam gravados?
              </h4>
              <p className="text-neutral-300">
                A gravação utiliza a <strong>Arquitetura Padrão da Indústria (Object Storage + Base de Dados Relacional/NoSQL)</strong>:
              </p>
            </div>

            <div className="grid grid-cols-1 sm:grid-cols-2 gap-2.5 pt-1 font-mono text-[11px]">
              <div className="p-3 bg-neutral-900 rounded-xl border border-white/5 space-y-1">
                <div className="text-amber-400 font-bold flex items-center gap-1">
                  <HardDrive className="w-3.5 h-3.5" /> 1. Object Storage (Ficheiros)
                </div>
                <p className="text-neutral-400 text-[10px]">
                  Os ficheiros binários (MP4, JPG) vão para <strong>Firebase Storage, Cloudflare R2 ou AWS S3</strong> com CDN global.
                </p>
              </div>

              <div className="p-3 bg-neutral-900 rounded-xl border border-white/5 space-y-1">
                <div className="text-green-400 font-bold flex items-center gap-1">
                  <Database className="w-3.5 h-3.5" /> 2. Base de Dados (Metadados)
                </div>
                <p className="text-neutral-400 text-[10px]">
                  A base de dados (PostgreSQL/Firestore) só guarda a URL em texto, a duração (ex: <code>7.8s</code>) e contadores de votos.
                </p>
              </div>
            </div>

            <div className="p-3 rounded-xl bg-amber-400/10 border border-amber-400/20 space-y-1">
              <h5 className="font-bold text-white text-xs flex items-center gap-1 font-mono">
                <Zap className="w-3.5 h-3.5 text-amber-400" /> A Base de Dados vai aguentar?
              </h5>
              <p className="text-neutral-300 text-[11px]">
                <strong>Sim, com folga infinita!</strong> Como a base de dados nunca guarda arquivos brutos e os vídeos têm o limite de <strong>8 segundos</strong> (pesando apenas 2MB–4MB por clipe), <strong>1 milhão de posts ocupa menos de 500MB</strong> na base de dados. O tráfego de vídeo é absorvido pelas CDNs sem sobrecarregar o servidor.
              </p>
            </div>

            <div className="relative">
              <button
                onClick={handleCopy}
                className="absolute top-2 right-2 px-2 py-1 rounded-lg bg-neutral-800 hover:bg-neutral-700 text-neutral-300 text-[10px] font-mono flex items-center gap-1 border border-white/10 z-10"
              >
                {copied ? <Check className="w-3 h-3 text-green-400" /> : <Copy className="w-3 h-3" />}
                {copied ? 'Copiado!' : 'Copiar Pipeline'}
              </button>
              <pre className="bg-black/60 p-3 rounded-xl border border-white/5 text-neutral-400 font-mono text-[10px] overflow-x-auto max-h-[160px] leading-relaxed">
                <code>{storagePipelineCode}</code>
              </pre>
            </div>
          </div>
        ) : activeSchemaTab !== 'flow' ? (
          <div className="relative">
            <button
              onClick={handleCopy}
              className="absolute top-3 right-3 px-2.5 py-1 rounded-lg bg-neutral-800/90 hover:bg-neutral-700 text-neutral-300 text-xs font-mono flex items-center gap-1 border border-white/10 z-10"
            >
              {copied ? <Check className="w-3.5 h-3.5 text-green-400" /> : <Copy className="w-3.5 h-3.5" />}
              {copied ? 'Copiado!' : 'Copiar'}
            </button>
            <pre className="bg-neutral-950 p-4 rounded-2xl border border-white/10 text-neutral-300 font-mono text-xs overflow-x-auto max-h-[380px] leading-relaxed">
              <code>{activeSchemaTab === 'sql' ? sqlSchemaCode : firestoreSchemaCode}</code>
            </pre>
          </div>
        ) : (
          /* Tab 4: Logic Breakdown */
          <div className="space-y-3 bg-neutral-950 p-4 rounded-2xl border border-white/10 text-xs text-neutral-300 leading-relaxed">
            <div className="space-y-1">
              <h4 className="font-bold text-white font-mono text-sm flex items-center gap-1.5">
                <span className="text-amber-400">1.</span> O Sistema de Glow de Aura
              </h4>
              <p className="text-neutral-400">
                O perfil do utilizador reflete a sua pontuação total com transição reativa:
              </p>
              <ul className="list-disc pl-5 space-y-1 text-neutral-300 font-mono text-[11px]">
                <li><strong className="text-neutral-400">0 - 999 Aura:</strong> Cinzento / NPC (Halo cinzento suave, sem brilho significativo)</li>
                <li><strong className="text-blue-400">1,000 - 4,999 Aura:</strong> Azul / Sigma Blue (Pulso elétrico azul neon)</li>
                <li><strong className="text-amber-400">5,000 - 9,999 Aura:</strong> Dourado / Sovereign (Aura radiante dourada pulsante)</li>
                <li><strong className="text-purple-300">10,000+ Aura:</strong> Cósmico / Branco Celestial (Arco-íris prismático & pulso cósmico)</li>
              </ul>
            </div>

            <div className="space-y-1 pt-2 border-t border-white/10">
              <h4 className="font-bold text-white font-mono text-sm flex items-center gap-1.5">
                <span className="text-green-400">2.</span> Aura Social (Votação em Tempo Real)
              </h4>
              <p className="text-neutral-400">
                Ao clicar em <strong>+ AURA</strong>, o autor recebe <strong>+100 Aura</strong> instantaneamente. Ao clicar em <strong>- AURA</strong>, o autor perde <strong>-50 Aura</strong>. A soma atualiza o ranking e o tier de Glow em tempo real.
              </p>
            </div>

            <div className="space-y-1 pt-2 border-t border-white/10">
              <h4 className="font-bold text-white font-mono text-sm flex items-center gap-1.5">
                <span className="text-amber-400">3.</span> Aura Disciplina (Habit Tracker Privado)
              </h4>
              <p className="text-neutral-400">
                Cada hábito completado no dia soma pontos de Aura fixos (ex: Ginásio +200, Leitura +120). O streak é incrementado consecutivamente, alimentando o perfil sem depender de validação social.
              </p>
            </div>
          </div>
        )}

        <div className="flex justify-end pt-2">
          <button
            onClick={onClose}
            className="px-5 py-2 rounded-xl bg-neutral-800 hover:bg-neutral-700 text-neutral-200 text-xs font-bold font-mono transition-colors"
          >
            Fechar
          </button>
        </div>
      </div>
    </div>
  );
};
